# TRAINING PARAMETERS
RESUME_FROM_CHECKPOINT: true
RESUME_OPTIM_FROM_CHECKPOINT: true
#CHECKPOINT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/ubdl/larflow/larmatchnet/larmatch/checkpoint.cc1gpu.78000th.tar" # larmatch v1 model
CHECKPOINT_FILE: "/cluster/tufts/wongjiradlabnu/twongj01/gen2/photon_analysis/ubdl/larflow/larmatchnet/larmatch/checkpoints/sparkling-sunset-78/checkpoint.44000th.tar"
LEARNING_RATE: 1.0e-4
WEIGHT_DECAY: 1.0e-4
NUM_ITERATIONS: 100000
START_ITER: 44001
DEVICE: cpu
RUN_PROFILER: false
BATCH_SIZE: 8
BATCH_TRIPLET_LIMIT: 4000000
CLIP_GRAD_NORM: false
TRAIN_ITER_PER_RECORD: 1
TRAIN_ITER_PER_VALIDPT: 10
NUM_VALID_ITERS: 1
ITER_PER_CHECKPOINT: 500
ITER_PER_CACHECLEAR: 1
VERBOSE_MAIN_LOOP: false
VERBOSE_ITER_LOOP: false
VERBOSE_LOSS: false
VERBOSE_ACCURACY: false
LOGGER: "wandb"
SEED: 3114

# DATASET PARAMETERS
TRAIN_DATASET_INPUT_TXTFILE: ""
TRAIN_DATASET_VERBOSE: false
VALID_DATASET_INPUT_TXTFILE: ""
VALID_DATASET_VERBOSE: false

# MODEL PARAMETERS
USE_FEATURE_DROPOUT: false
USE_SEPARATE_SSNET_DECODER: false

# LOSS PARAMETERS
USE_LEARNABLE_LOSS_WEIGHTS: true
INIT_LM_LOSS_WEIGHT: -2.9
INIT_KP_LOSS_WEIGHT: -2.1
RUN_LARMATCH: true
RUN_SSNET: true
RUN_KPLABEL: true
RUN_KPSHIFT: false
RUN_PAF: true
