#!/bin/bash

LANTERN_ANA_REPO_DIR=$PWD
LANTERN_ANA_BIN_DIR=${LANTERN_ANA_REPO_DIR}/bin
[[ ":$PYTHONPATH:" != *":${LANTERN_ANA_REPO_DIR}:"* ]] && export PYTHONPATH="${LANTERN_ANA_REPO_DIR}:${PYTHONPATH}"
[[ ":$PATH:" != *":${LANTERN_ANA_BIN_DIR}:"* ]] && export PATH="${LANTERN_ANA_BIN_DIR}:${PATH}"
